# Generated by Django 4.1.3 on 2022-12-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_address_listing_body_style_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
